# Generated by Django 6.0.3 on 2026-04-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name in English')),
                ('icon', models.CharField(blank=True, default='fas fa-box', max_length=50, verbose_name='أيقونة')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المصنع بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='Factory Name in English')),
                ('description_ar', models.TextField(blank=True, verbose_name='وصف المصنع بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='Factory Description in English')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('owner_name', models.CharField(max_length=200, verbose_name='اسم صاحب المصنع')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='factories/', verbose_name='شعار المصنع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مصنع',
                'verbose_name_plural': 'المصانع',
            },
        ),
        migrations.CreateModel(
            name='FactoryListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name_ar', models.CharField(max_length=200, verbose_name='اسم المصنع بالعربية')),
                ('factory_name_en', models.CharField(blank=True, max_length=200, verbose_name='Factory Name in English')),
                ('owner_name', models.CharField(max_length=200, verbose_name='اسم صاحب المصنع')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('products_description_ar', models.TextField(verbose_name='وصف المنتجات المراد عرضها')),
                ('products_description_en', models.TextField(blank=True, verbose_name='Products Description in English')),
                ('commercial_register', models.CharField(blank=True, max_length=100, verbose_name='رقم السجل التجاري')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('additional_notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('contacted', 'تم التواصل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
            ],
            options={
                'verbose_name': 'طلب عرض مصنع',
                'verbose_name_plural': 'طلبات عرض المصانع',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المنتج بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='Product Name in English')),
                ('description_ar', models.TextField(verbose_name='وصف المنتج بالعربية')),
                ('description_en', models.TextField(verbose_name='Product Description in English')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر الأدنى (USD)')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر الأقصى (USD)')),
                ('min_order_quantity', models.CharField(blank=True, max_length=100, verbose_name='الحد الأدنى للطلب')),
                ('availability', models.CharField(choices=[('available', 'متوفر'), ('seasonal', 'موسمي'), ('on_order', 'عند الطلب')], default='available', max_length=20, verbose_name='التوفر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='exports.category', verbose_name='التصنيف')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='exports.factory', verbose_name='المصنع')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('product_interest', models.CharField(max_length=300, verbose_name='المنتج / السلعة المطلوبة')),
                ('quantity_needed', models.CharField(blank=True, max_length=100, verbose_name='الكمية المطلوبة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='exports.product', verbose_name='المنتج المطلوب')),
            ],
            options={
                'verbose_name': 'استفسار مستثمر',
                'verbose_name_plural': 'استفسارات المستثمرين',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
